# Generated by Django 5.0.3 on 2024-04-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0002_message_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
    ]
