# Generated by Django 5.0.3 on 2024-04-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0004_remove_message_reciepient_message_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='reciepient',
        ),
    ]
