# Generated by Django 5.0.3 on 2024-04-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0007_remove_message_recipient_message_reciepient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciepient',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
