# Generated by Django 5.0.3 on 2024-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profil_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='first_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profil',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profil',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
