# Generated by Django 5.0.3 on 2024-04-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_profil_first_name_profil_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
