# Generated by Django 5.0.3 on 2024-04-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_profil_email_alter_profil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
