# Generated by Django 5.0.3 on 2024-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_alter_profil_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
