# Generated by Django 5.0.3 on 2024-04-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_alter_profil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
